name: '[CDM] Build and test'

on:
  workflow_call:
    inputs:
      static-build:
        type: boolean
        required: true
      upload:
        type: boolean
        required: true

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04,  macos-26, windows-2025]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Clone cdm-devkit
        run: |
          git clone --depth 1 https://github.com/cdm-processors/cdm-devkit.git cdm-devkit
      - name: Install `cdm-devkit` package
        run: pip install -e cdm-devkit
      - name: Build cdm-devkit
        run: |
          cd cdm-devkit
          poetry build
      - name: Enable MSVC Dev (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Remove GNU Link (Windows)
        if: runner.os == 'Windows'
        run: |
          rm /usr/bin/link
      - name: Build LLVM (static linking)
        if: inputs.static-build && runner.os == 'Linux'
        run: |
          ./llvm/utils/cdm/build.py --static -j 2 -v
      - name: Build LLVM (dynamic linking)
        if: runner.os != 'Linux' || (!inputs.static-build)
        run: |
          ./llvm/utils/cdm/build.py -j 2 -v
      - name: Run end-to-end tests
        continue-on-error: true
        run: make -C llvm/test_cdm SHELL=bash CLANG=$(realpath llvm/build/bin/clang) test
      - name: Run lit tests
        run: ./llvm/build/bin/llvm-lit ./llvm/test/CodeGen/CDM
      - name: Platform variable
        run: |
          PLATFORM_OS=${{ runner.os }}
          PLATFORM_OS=$( echo $PLATFORM_OS | tr '[:upper:]' '[:lower:]' )
          PLATFORM_ARCH=$(uname -m)
      - name: Compress artifacts (tarball)
        if: inputs.upload && (runner.os != 'Windows')
        run: |
          tar --strip-components=2 \
            -czvf \
            clang-cdm-${PLATFORM_OS}-${PLATFORM_ARCH}.tar.gz \
            llvm/build/bin
      - name: Compress artifacts (zip.. ball?)
        if: inputs.upload && (runner.os == 'Windows')
        run: |
          tar --strip-components=2 -a -c -f clang-cdm-${PLATFORM_OS}-${PLATFORM_ARCH}.zip llvm/build/bin
      - name: Upload artifacts
        if: inputs.upload
        uses: actions/upload-artifact@v6
        with:
          compression-level: 0
          name: ${{ matrix.os }}
          path: |
            *.tar.gz
            *.zip
