name: '[CDM] Release binaries'

on:
  push:
    tags:
      - 'ver-*'

jobs:
  build-test:
    uses: ./.github/workflows/cdm-build.yaml
    with:
      static-build: true
      upload: true

  release:
    needs: build-test
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Create subfolder
        run: mkdir artifacts_download
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          run-id: ${{ needs.build-test.outputs.run-id }}
          path: ./artifacts_download
      - name: Print files list
        run: find .
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: clang with CdM-16 support release ${{github.ref_name}}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ${{github.workspace}}/artifacts_download/*.zip
