name: '[CDM] Nightly build'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *" # every day 21:00 UTC (4:00 UTC+7)

jobs:
  build-test:
    permissions:
      actions: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Guard
        continue-on-error: true
        run: "[[ $(git describe --tags) == nightly ]] && exit 1"
      - name: Shutdown
        if: failure()
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}
        env:
          GH_TOKEN: ${{ secrets. GITHUB_TOKEN }}
      - uses: ./.github/workflows/cdm-build.yaml
        with:
          static-build: true
          upload: true

  release:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Create subfolder
        run: mkdir artifacts_download
      - name: Download artifacts
        uses: actions/download-artifact@v7
        with:
          path: ./artifacts_download
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly'
          body: 'Nightly releases are made every night. They contain the newest features and fixes, but may be unstable.'
          prerelease: true
          files: |
            ${{github.workspace}}/artifacts_download/*/*.tar.gz
            ${{github.workspace}}/artifacts_download/*/*.zip

