name: '[CDM] Build and test'

on:
  workflow_call:
    inputs:
      static-build:
        type: boolean
        required: true
      upload:
        type: boolean
        required: true

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04,  macos-26]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Clone cdm-devkit
        run: |
          git clone --depth 1 \
            https://github.com/cdm-processors/cdm-devkit.git \
            cdm-devkit
      - name: Install `cdm-devkit` package
        run: pip install -e cdm-devkit
      - name: Build cdm-devkit
        run: |
          cd cdm-devkit
          poetry build
      - name: Build LLVM
        ## as of now macos doesn't support building LLVM staticly
        run: |
          ./llvm//utils/cdm/build.py -j 2 \
            -use-ninja \
            -verbose \
            ${{ inputs.static-build && !contains(matrix.os, 'macos') && '-static' || '' }}
      - name: Run end-to-end tests
        run: make -C llvm/test_cdm CLANG=$(realpath llvm/build/bin/clang) test
      - name: Run lit tests
        run: ./llvm/build/bin/llvm-lit ./llvm/test/CodeGen/CDM
      - name: Upload artifacts
        if: inputs.upload == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: clang-cdm-${{ matrix.os }}
          path: ./llvm/build/bin
